version: '3.8'

services:
  app:
    build: .
    container_name: saas2024-13
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./db:/app/db
      - .:/app